- name: Install Git on Azure VMs
  hosts: azure_vms
  become: true

  vars:
    terraform_version: "1.7.5"  # Change this to your desired version
    install_dir: "/usr/local/bin"
    terraform_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"

  tasks:
  
  
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Check if Terraform is already installed
      stat:
        path: "{{ install_dir }}/terraform"
      register: terraform_installed

    - name: Create temporary directory for download
      tempfile:
        state: directory
        suffix: terraform
      register: temp_dir

    - name: Download Terraform
      when: not terraform_installed.stat.exists
      get_url:
        url: "{{ terraform_url }}"
        dest: "{{ temp_dir.path }}/terraform.zip"
        mode: '0755'

    - name: Install unzip if needed
      when: not terraform_installed.stat.exists
      package:
        name: unzip
        state: present

    - name: Extract Terraform
      when: not terraform_installed.stat.exists
      unarchive:
        src: "{{ temp_dir.path }}/terraform.zip"
        dest: "{{ temp_dir.path }}"
        remote_src: yes
        mode: '0755'

    - name: Install Terraform binary
      when: not terraform_installed.stat.exists
      copy:
        src: "{{ temp_dir.path }}/terraform"
        dest: "{{ install_dir }}/terraform"
        remote_src: yes
        mode: '0755'
        owner: root
        group: root

    - name: Verify Terraform installation
      command: "terraform version"
      register: terraform_version_check
      changed_when: false
      failed_when: false

    - name: Display Terraform version
      debug:
        msg: "{{ terraform_version_check.stdout }}"

    - name: Clean up temporary directory
      file:
        path: "{{ temp_dir.path }}"
        state: absent
        
        
    - name: Clone Git repository
      git:
        repo: https://github.com/RichardPatrick-dev/devops.git
        dest: /home/azureuser/terraform-scripts
        clone: yes
        update: no
        
    - name: Clean up files (example)
      file:
        path: /home/azureuser/terraform-scripts
        state: absent
