- name: Install Git on Azure VMs
  hosts: azure_vms
  become: true

  vars:
    terraform_version: "1.7.5"  # Change this to your desired version
    install_dir: "/usr/local/bin"
    terraform_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"

  tasks:
  
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Terraform
      import_tasks: Task/install_terraform.yml

        
    - name: Clone Git repository
      git:
        repo: https://github.com/RichardPatrick-dev/devops.git
        dest: /home/azureuser/terraform-scripts
        clone: yes
        update: no
        
    - name: Clean up files (example)
      file:
        path: /home/azureuser/terraform-scripts
        state: absent
